
# Homework 1
## Neural Networks and Fuzzy Systems
### Exercise 2-2 - Flights

Daniel Gonzalez - 12/02/2025

We start loading libraries

In [1]:
import pandas as pd
import numpy as np

We read the data with help from pandas as pd

In [12]:
flights = pd.read_csv('nycflights13.csv')
flights.shape
flights.head()

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
0,2013,1,1,517.0,2.0,830.0,11.0,UA,N14228,1545,EWR,IAH,227.0,1400,5.0,17.0
1,2013,1,1,533.0,4.0,850.0,20.0,UA,N24211,1714,LGA,IAH,227.0,1416,5.0,33.0
2,2013,1,1,542.0,2.0,923.0,33.0,AA,N619AA,1141,JFK,MIA,160.0,1089,5.0,42.0
3,2013,1,1,544.0,-1.0,1004.0,-18.0,B6,N804JB,725,JFK,BQN,183.0,1576,5.0,44.0
4,2013,1,1,554.0,-6.0,812.0,-25.0,DL,N668DN,461,LGA,ATL,116.0,762,5.0,54.0

### 1. Rename Columns

To change column names we create a list with all the columns and their new name to have all items at hand.
Then with rename we take our list of new names

In [44]:
new_names = {
    'year': 'Year',
    'month': 'Month',
    'day': 'Day',
    'dep_time': 'Departure_Time',
    'dep_delay': 'Departure_Delay',
    'arr_time': 'Arrival_Time',
    'arr_delay': 'Arrival_Delay',
    'carrier': 'Airline',
    'tailnum': 'Tail_Number',
    'flight': 'Flight_Number',
    'origin': 'Origin',
    'dest': 'Destination',
    'air_time': 'Flight_Time',
    'distance': 'Distance',
    'hour': 'Hour',
    'minute': 'Minute'
}
flights = flights.rename(columns=new_names)

### 2. Filter the flights from and to JFK (or any other airport)

For this we check the columns "Origin" and "Destination" if the register mention "JFK" then we save the information in the table "flights_JFK"

In [52]:
flights_JFK = flights[(flights['Origin'] == 'JFK') | (flights['Destination'] == 'JFK')]
flights_JFK.shape
flights_JFK.head()

,Year,Month,Day,Departure_Time,Departure_Delay,Arrival_Time,Arrival_Delay,Airline,Tail_Number,Flight_Number,Origin,Destination,Flight_Time,Distance,Hour,Minute
2,2013,1,1,542.0,2.0,923.0,33.0,AA,N619AA,1141,JFK,MIA,160.0,1089,5.0,42.0
3,2013,1,1,544.0,-1.0,1004.0,-18.0,B6,N804JB,725,JFK,BQN,183.0,1576,5.0,44.0
8,2013,1,1,557.0,-3.0,838.0,-8.0,B6,N593JB,79,JFK,MCO,140.0,944,5.0,57.0
10,2013,1,1,558.0,-2.0,849.0,-2.0,B6,N793JB,49,JFK,PBI,149.0,1028,5.0,58.0
11,2013,1,1,558.0,-2.0,853.0,-3.0,B6,N657JB,71,JFK,TPA,158.0,1005,5.0,58.0

For this we create a column named "Category" in where we will add the type of flight Outgoing/Incoming.

If Origin or Destination match with "JFK" then will be asigned the proper category.

After that we concat both df and we sort the registers to group them.

In [61]:
# Outocomings
out_flights = flights_JFK[flights_JFK['Origin'] == 'JFK']
out_flights['Category'] = 'Outgoing'  # Add Outgoing to results

# Incomings
in_flights = flights_JFK[flights_JFK['Destination'] == 'JFK']
in_flights['Category'] = 'Incoming'  # Add Incoming to results

# Concat df
combined_df = pd.concat([out_flights, in_flights])

# Sort by category
combined_df.set_index(['Category', combined_df.groupby('Category').cumcount()], inplace=True)

combined_df.shape
combined_df.head()

            Year  Month  Day  Departure_Time  Departure_Delay  Arrival_Time  \
Category
Outgoing 0  2013      1    1           542.0              2.0         923.0
         1  2013      1    1           544.0             -1.0        1004.0
         2  2013      1    1           557.0             -3.0         838.0
         3  2013      1    1           558.0             -2.0         849.0
         4  2013      1    1           558.0             -2.0         853.0

            Arrival_Delay Airline Tail_Number  Flight_Number Origin  \
Category
Outgoing 0           33.0      AA      N619AA           1141    JFK
         1          -18.0      B6      N804JB            725    JFK
         2           -8.0      B6      N593JB             79    JFK
         3           -2.0      B6      N793JB             49    JFK
         4           -3.0      B6      N657JB             71    JFK

           Destination  Flight_Time  Distance  Hour  Minute
Category
Outgoing 0         MIA        160.0      1089   5.0    42.0
         1         BQN        183.0      1576   5.0    44.0
         2         MCO        140.0       944   5.0    57.0
         3         PBI        149.0      1028   5.0    58.0
         4         TPA        158.0      1005   5.0    58.0

### 3. In each category reorder the flights based on delay time in Ascending order (from smallest to greatest)

With help from sort_values we use the "Departure Delay" column to create a new df with sorted items, then we repeat last process to concat the df from outcoming and incomings.

In [70]:

out_flights_delay = out_flights.sort_values(by =['Departure_Delay'], ascending=True) #ascending=True for smallest to gratest
in_flights_delay = in_flights.sort_values(by =['Departure_Delay'], ascending=True)   #         =False for greatest to smallest

combined_df_delay = pd.concat([out_flights_delay, in_flights_delay])
combined_df_delay.set_index(['Category', combined_df_delay.groupby('Category').cumcount()], inplace=True)

combined_df_delay.shape
combined_df_delay

                 Year  Month  Day  Departure_Time  Departure_Delay  \
Category
Outgoing 0       2013     12    7          2040.0            -43.0
         1       2013      3    2          1431.0            -24.0
         2       2013      5   18          1912.0            -23.0
         3       2013      2    6          1528.0            -22.0
         4       2013      9   14          2223.0            -22.0
...               ...    ...  ...             ...              ...
         111274  2013      9   24             NaN              NaN
         111275  2013      9   24             NaN              NaN
         111276  2013      9   25             NaN              NaN
         111277  2013      9   28             NaN              NaN
         111278  2013      9   30             NaN              NaN

                 Arrival_Time  Arrival_Delay Airline Tail_Number  \
Category
Outgoing 0               40.0           48.0      B6      N592JB
         1             1601.0          -30.0      9E      N929XJ
         2             2126.0            7.0      9E      N800AY
         3             1750.0          -36.0      9E      N923XJ
         4             2327.0          -24.0      B6      N274JB
...                       ...            ...     ...         ...
         111274           NaN            NaN      MQ      N834MQ
         111275           NaN            NaN      MQ      N720MQ
         111276           NaN            NaN      EV      N877AS
         111277           NaN            NaN      AA      N320AA
         111278           NaN            NaN      9E         NaN

                 Flight_Number Origin Destination  Flight_Time  Distance  \
Category
Outgoing 0                  97    JFK         DEN        265.0      1626
         1                3318    JFK         BUF         55.0       301
         2                4127    JFK         IAD         45.0       228
         3                3427    JFK         IND        109.0       665
         4                1816    JFK         SYR         41.0       209
...                        ...    ...         ...          ...       ...
         111274           3370    JFK         DCA          NaN       213
         111275           3621    JFK         DCA          NaN       213
         111276           5716    JFK         IAD          NaN       228
         111277              1    JFK         LAX          NaN      2475
         111278           3393    JFK         DCA          NaN       213

                 Hour  Minute
Category
Outgoing 0       20.0    40.0
         1       14.0    31.0
         2       19.0    12.0
         3       15.0    28.0
         4       22.0    23.0
...               ...     ...
         111274   NaN     NaN
         111275   NaN     NaN
         111276   NaN     NaN
         111277   NaN     NaN
         111278   NaN     NaN

[111279 rows x 16 columns]